// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QPhising.Api.Infrastructure.Persistence;

#nullable disable

namespace QPhising.Api.Migrations
{
    [DbContext(typeof(QPhisingDbContext))]
    [Migration("20260419111901_firstind")]
    partial class firstind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.CampaignEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ScheduleEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("schedule_ends_at_utc");

                    b.Property<DateTimeOffset?>("ScheduleStartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("schedule_starts_at_utc");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TrackingPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_page_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TrackingPageId")
                        .IsUnique();

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)")
                        .HasColumnName("html_content");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.TrackingPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("CaptureUtmParameters")
                        .HasColumnType("boolean")
                        .HasColumnName("capture_utm_parameters");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomHtmlContent")
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)")
                        .HasColumnName("custom_html_content");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool?>("EnableBotFiltering")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_bot_filtering");

                    b.Property<bool?>("MaskIpAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("mask_ip_address");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.Property<int>("PublishState")
                        .HasColumnType("integer")
                        .HasColumnName("publish_state");

                    b.Property<int?>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("tracking_pages", (string)null);
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.VisitEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("IpAddressHashPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("ip_address_hash_policy");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReferrerUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("referrer_url");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TrackingPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_page_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("user_agent");

                    b.Property<string>("VisitorFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("visitor_fingerprint");

                    b.HasKey("Id");

                    b.HasIndex("TrackingPageId", "OccurredAtUtc");

                    b.HasIndex("TrackingPageId", "SessionId", "OccurredAtUtc");

                    b.ToTable("visit_events", (string)null);
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.CampaignEntity", b =>
                {
                    b.HasOne("QPhising.Api.Infrastructure.Persistence.Entities.TrackingPageEntity", null)
                        .WithMany()
                        .HasForeignKey("TrackingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.TrackingPageEntity", b =>
                {
                    b.HasOne("QPhising.Api.Infrastructure.Persistence.Entities.TemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.VisitEventEntity", b =>
                {
                    b.HasOne("QPhising.Api.Infrastructure.Persistence.Entities.TrackingPageEntity", "TrackingPage")
                        .WithMany("VisitEvents")
                        .HasForeignKey("TrackingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackingPage");
                });

            modelBuilder.Entity("QPhising.Api.Infrastructure.Persistence.Entities.TrackingPageEntity", b =>
                {
                    b.Navigation("VisitEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
